### PR TITLE
Add a configuration file

### PR DESCRIPTION
**Pull request by WalternativE**
Addresses issue https://github.com/LambdaFactory/Fornax/issues/1

- To allow exclusions of files and folders that should not be handled by generators
- To allow a single entry point for less/scss bundles

### CODE REVIEW

**Comment by WalternativE** [comment]
I'd propose this as a possible approach to have a config file for fornax. I looked into toml but didn't find it feasible to build the needed parts. @Krzysztof-Cieslak @pblasucci do you want to give feedback on my proposed changes? As far as I see you two thought the most about fornax configs.

I'm happy to adapt the current draft according to your feedback 😊

**Comment by Krzysztof-Cieslak** [comment]
Hey, this looks good to me.

Two small ideas for improvements:
- Maybe `_site.yml` instead of `_siteModel.yml`?
- Maybe we should by default ignore anything that starts with `_`?

**Comment by WalternativE** [comment]
Renaming `_siteModel.yml` makes a lot of sense. I'll change that.
I think as a default ignoring stuff that starts with `_` is a good idea. I know of the sass convention to use leading underscores for variable, mixin and other module files - these should be ignored anyway as they usually are referenced in the `scss` entry point file. I'll also look into that. 🙇‍♂️

**Comment by Krzysztof-Cieslak** [comment]
This will be handled differently in #40

**Pull request closed without merging**
