### PR TITLE
Cannot render tables

### PR DESCRIPTION
**Pull request by WalternativE**
I decided to create this PR in relation to https://github.com/LambdaFactory/Fornax/issues/16 as there has been no activity for a couple of months. Still, all changes where originally implemented by @grishace - I just condensed them a bit and made some adjustments.

I thought that directly referencing the Markdig spec sites would be beneficial as tables aren't part of the CommonMark spec. I also decided to only include the table extensions as I didn't want to just decide willy-nilly if this is a good idea. Should be part of another issue and PR (if not solved by the possibility to supply one's own render function as suggested in the original issue it should be at least configurable).

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Hey, can you rebase this one please?

**Comment by WalternativE** [comment]
> Hey, can you rebase this one please?

Aye. Will do this on my commute back home.

**Comment by WalternativE** [comment]
> 
> 
> Hey, can you rebase this one please?

Done 👨‍💻

**Comment by Krzysztof-Cieslak** [comment]
Cheers!

**Pull request merged**
